.ci/CloneTest.ps1, .ci/check-core.yml, .ci/check-installer.yml, .ci/run-compliance-tests.yml, .ci/testSettings.runsettings
=> Update CI files

LifeCycleAssessment_Engine/Convert/ToEnvironmentalProductDeclarationData.cs, LifeCycleAssessment_Engine/Convert/ToHealthProductDeclarationData.cs, LifeCycleAssessment_Engine/Convert/ToSectorEnvironmentalProductDeclarationData.cs, LifeCycleAssessment_oM/EnvironmentalProductDeclaration.cs, LifeCycleAssessment_oM/HealthProductDeclaration.cs, LifeCycleAssessment_oM/SectorEnvironmentalProductDeclaration.cs
=> Updating to remove source property

LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
=> Add reference to Physical_oM

LifeCycleAssessment_Engine/Compute/BenchmarkVariance.cs, LifeCycleAssessment_Engine/Compute/ConcreteVolume.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/AcidificationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/DepletionOfAbioticResources.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/DepletionOfAbioticResourcesFossilFuels.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/EutrophicationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/AcidificationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/DepletionOfAbioticResources.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/DepletionOfAbioticResourcesFossilFuels.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/EutrophicationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/GlobalWarmingPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/OzoneDepletionPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/ExplicitMethods/PhotochemicalOzoneCreationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/GlobalWarmingPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/OzoneDepletionPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/PhotochemicalOzoneCreationPotential.cs, LifeCycleAssessment_Engine/Compute/GlazingVolume.cs, LifeCycleAssessment_Engine/Compute/MaterialEndOfLife.cs, LifeCycleAssessment_Engine/Compute/ReinforcementVolume.cs, LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
=> Migration of methods from ClimateEmergency_Toolkit

LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
https://github.com/BHoM/admin/issues/5
Closes #
=> Update references and post build

LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclaration.cs
Closes #109 
Fixes false warnings.
Any file evaluating an lca that includes objects that are not IElementM's with epds of QuantityType and with a volume property.
=> Cleaned up warnings

LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessment.cs
=> EvalScope method multiplication of results fix

LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessmentScope.cs, LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj, LifeCycleAssessment_Engine/Query/GetEvaluationValue.cs, LifeCycleAssessment_Engine/Query/IsValid.cs
https://github.com/BHoM/BHoM/pull/1024
Closes #151 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LifeCycleAssessment_Toolkit/LifeCycleAssessment_oM-%231023%20MEPScope%20refactor.gh?csf=1&web=1&e=T6Ln1K)
=> MEPScope refactor

LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial
Only adding a reference so can be merged before the rest
=> Aligning with changes to ShapeProfiles

LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/AcidificationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/DepletionOfAbioticResources.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/DepletionOfAbioticResourcesFossilFuels.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/EutrophicationPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/GlobalWarmingPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/OzoneDepletionPotential.cs, LifeCycleAssessment_Engine/Compute/EnvironmentalProductDeclarationMetrics/PhotochemicalOzoneCreationPotential.cs, LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclaration.cs, LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclarationByArea.cs, LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclarationByMass.cs, LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclarationByVolume.cs, LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessmentScope.cs, LifeCycleAssessment_Engine/Compute/MaterialEndOfLife.cs, LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj, LifeCycleAssessment_Engine/Query/EnvironmentalProductDeclaration.cs, LifeCycleAssessment_Engine/Query/GetEvaluationValue.cs, LifeCycleAssessment_Engine/Query/GetFragmentQuantityType.cs, LifeCycleAssessment_Engine/Query/MaterialEndOfLifeTreatment.cs
https://github.com/BHoM/BHoM/pull/1038
Closes #137 
Closes #154 
Closes #146 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/LifeCycleAssessment_oM/LifeCycleAssessment_oM-%231035%20Interface%20Changes_Small.gh?csf=1&web=1&e=GGmlQF)
- IElementM replaces IBHoMObject for all method inputs. Objects are still cast to IBHoMObject for any subsequent BHoMObject specific queries (BHoM_Guid for example) but are no longer used for inputs.
- Core compute method cleanup and restructuring ```EvaluateEnvironmentalProductDeclarationByObject()```
- Removal of unused namespaces
- MaterialEndOfLifeTreatment switch to Query from Compute
=> Implement more strict interface and remove CustomData

LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessmentScope.cs, LifeCycleAssessment_Engine/Query/GetEvaluationValue.cs
https://github.com/BHoM/BHoM/pull/1069
Closes #158
=> Update MEP Namespaces for Eval Methods

.github/CODEOWNERS
=> Remove Codeowners file

LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclaration.cs, LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclarationByVolume.cs
Closes #163 
Closes #132 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LifeCycleAssessment_Toolkit/LifeCycleAssessment_Toolkit-%23163%20Wrapper%20UI%20Messages.gh?csf=1&web=1&e=3a1uNN)
=> Inform the user of specific method called by wrapper

LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclaration.cs, LifeCycleAssessment_Engine/Query/GetEvaluationValue.cs, LifeCycleAssessment_Engine/Query/GetFragmentQuantityType.cs, LifeCycleAssessment_Engine/Query/GetQuantityType.cs, LifeCycleAssessment_Engine/Query/GetQuantityTypeValue.cs
=> Versioning Update to 4.1

LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj, LifeCycleAssessment_Engine/Query/ProjectLifeCycleAssessmentResults.cs
https://github.com/BHoM/BHoM/pull/1188
Closes #201 
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/LifeCycleAssessment_oM/%231187-ProjectLCA.gh?csf=1&web=1&e=0X5bgZ)
=> ProjectLCAResults Query

LifeCycleAssessment_Engine/Query/ProjectLifeCycleAssessmentResults.cs
Closes #214 
[here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/LifeCycleAssessment_Toolkit/%23214-Results-Query/Distinct%20ElementScope%20List.gh?csf=1&web=1&e=md6QuB)
=> Project LCA Query return distinct list of ElementScope

LifeCycleAssessment_Engine/Compute/EvaluateReferenceValue.cs
Closes #212 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/LifeCycleAssessment_Toolkit/%23212-EvaluateRefValue/EvalRefValue.gh?csf=1&web=1&e=WiHBHn)
=> Updates to Evaluate Reference Value

LifeCycleAssessment_Engine/Properties/AssemblyInfo.cs
Update Assembly Information to include description
=> Update Assembly Information

.ci/BHoMBot/Nuget/BHoM.Interop.LifeCycleAssessment.nuspec
=> Add nuspec template file

LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
=> Fix project file

.ci/unit-tests/LifeCycleAssessment_Engine_Tests/LifeCycleAssessment_Engine_Tests.csproj, LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
Update AssemblyFileVersion to 7.3
Remove previous version attributes
=> Update AssemblyFileVersion to 7.3
